language: golang

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

env:
  global:
  - GOPATH="$HOME/gopath"
  - PATH="$HOME/gopath/bin:$HOME/bin:$PATH"

install:
 - go get github.com/vanng822/css
 - go get github.com/vanng822/r2router
 - go get github.com/unrolled/render
 - go get github.com/vanng822/go-premailer/premailer
 - go get github.com/PuerkitoBio/goquery
 - go get golang.org/x/net/html
 - go get github.com/stretchr/testify/assert
 - go get github.com/fzipp/gocyclo

script:
  - make gocyclo_all test
